---
# Deployment manifest​
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s291468
spec:
  selector:
    matchLabels:
      app: s291468
  replicas: 1
  template:
    metadata:
      labels:
        app: s291468
    spec:
      containers:
      - name: s291468
        image: luigiferrettino/hugopipe:${IMG_TAG}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
# Service manifest
apiVersion: v1
kind: Service
metadata:
  name: s291468
  labels:
    app: s291468
spec:
  selector:
    app: s291468
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: ClusterIP
---
# Ingress manifest​
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s291468
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - s291468.crownlabs.polito.it
    secretName: hugo-site-cert
  rules:
  - host: s291468.crownlabs.polito.it
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: s291468
              port:
                number: 80
